drop type any_data_compound force;
drop type any_type force;
drop type any_type_mapper force;
drop type any_data force;
drop type any_data_attribute force;
drop type any_data_tab force;
drop type any_data_number force;
drop type any_data_object force;
drop type any_data_collection force;
drop package any_data_mapper;
drop type any_data_builder force;
