sudo: required

services:
  - docker

env:
  global:
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib
    - DATABASE_VERSION=11.2.0.2
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter

before_install:
  - docker pull wnameless/oracle-xe-11g
  - docker run -d -p 49160:22 -p 1521:1521 wnameless/oracle-xe-11g
#  - docker run -d -p 22:22 -p 1521:1521 wnameless/oracle-xe-11g
  - chmod +x .travis/setup_accounts.sh

install:
  - .travis/setup_accounts.sh
  - bundle install

language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec rake
